### PR TITLE
Make function in grub.cfg

### PR DESCRIPTION
**Pull request by Jonathan50**
Untested. May not work.
Any ideas for improvement?

### CODE REVIEW

**Comment by Jonathan50** [comment]
See https://www.gnu.org/software/grub/manual/html_node/Shell_002dlike-scripting.html or `info grub -n "shell-like scripting"`

**Comment by TheMatrixShibe** [comment]
Yes please. Merging.

**Comment by Jonathan50** [comment]
Oops. It tries to load `vmlinuz32` or `vmlinuz64` instead of `vmlinux32` or `vmlinux64`.

**Comment by Jonathan50** [comment]
See #5

**Pull request merged**
